DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS categories;
DROP TABLE IF EXISTS events;

CREATE TABLE IF NOT EXISTS users (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     name VARCHAR(255) NOT NULL,
                                     email VARCHAR(512) NOT NULL,
                                     CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
);
CREATE TABLE IF NOT EXISTS categories (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     name VARCHAR(255) NOT NULL,
                                     CONSTRAINT UQ_CATEGORY_NAME UNIQUE (name)
);
CREATE TABLE IF NOT EXISTS events (
                                     id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
                                     annotation VARCHAR(255) NOT NULL,
                                     description VARCHAR(255),
                                     title VARCHAR(255) NOT NULL,
                                     state VARCHAR(50),
                                     created_on TIMESTAMP WITHOUT TIME ZONE,
                                     event_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
                                     published_on TIMESTAMP WITHOUT TIME ZONE,
                                     is_paid BOOL NOT NULL,
                                     request_moderation BOOL,
                                     participant_limit BIGINT,
                                     views BIGINT,
                                     initiator_id BIGINT NOT NULL,
                                     category_id BIGINT NOT NULL,
                                     CONSTRAINT fk_events_to_users FOREIGN KEY(initiator_id) REFERENCES users(id),
                                     CONSTRAINT fk_events_to_categories FOREIGN KEY(category_id) REFERENCES categories(id)
);