version: '3.1'
services:
  stats-server:
    build: ./stats-server
    image: stats_server
    container_name: stats_server
    depends_on:
      - stats-db
    ports:
      - "9090:9090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/stats
      - POSTGRES_PASSWORD=password

  stats-db:
    image: postgres:14-alpine
    container_name: stats_db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=stats
      - POSTGRES_PASSWORD=password

  ewm-service:
    build: ./ewm-service
    image: ewm_service
    container_name: ewm_service
    depends_on:
      - ewm-db
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/ewm
      - POSTGRES_PASSWORD=password

  ewm-db:
    image: postgres:14-alpine
    container_name: ewm_db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=ewm
      - POSTGRES_PASSWORD=password
